# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

executors:
  node10-browsers:
    docker:
      - image: circleci/node:10-browsers

jobs:
  setup:
    executor: node10-browsers
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: make clean-dependencies
      - run: make deps
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - src
            - node_modules
            - test
  tests:
    executor: node10-browsers
    parallelism: 2
    steps:
      - attach_workspace:
          at: ./
      - run: npm run test:node
      - run: npm run test:browser

workflows:
  version: 2
  Implementations:
    jobs:
      - setup
      - tests:
          requires:
            - setup
